### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Thomashehe** [qbcore-framework/qb-shops#103]
**Describe the bug**
I have a problem where the peds are invisible in all the shops... the thing is that some can see them and some not.

**Expected behavior**
The bed should be there all the time

**Screenshots**
https://imgur.com/AGM45fm - This is me 
https://imgur.com/FsF6FoE - This is my friend

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] = We are on a month old qb-core
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] = basic qb-target
 - Have you renamed `qb-` to something custom? [e.g. yes/no] = no

**Comment by peppinoita** [comment]
I found how to reproduce.
This happens when a people perform logout in the apartment.
After logout and login you are not able to see ped in the shops.

**Comment by HUNT3RxLG** [comment]
I am also having the same issue but this is city wide and has nothing to do with changing characters. it does this even after a city restart now if i do a manual restart in the live city then the peds come back and everything works until the next restart

**Comment by popmaster10** [comment]
Is this still an issue? Cause I'm having this issue as well
