### ISSUE TITLE
Shops will not open. 

### ISSUE THREAD

**Issue by WillIShocker** [qbcore-framework/qb-shops#104]
No shops on the entire map will open. 24/7, hardware, ammunation. Target or E presents to open, but will not actually open the shop. Console doesnt show any errors.

**Comment by WillIShocker** [comment]
No shops on the entire map will open. 24/7, hardware, ammunation. Target or E presents to open, but will not actually open the shop.

**Comment by BerkieBb** [comment]
And you didn't make any modifications to the inventory?

**Comment by WillIShocker** [comment]
Apologies, I fixed this ages ago. I forgot to mark solved or close the issue. Thats my bad.

**Comment by Branzey1214** [comment]
How did you fix it if you do not mind because i am having the same issue
