### ISSUE TITLE
[BUG] requiresLicense are gone 

### ISSUE THREAD

**Issue by ARSSANTO** [qbcore-framework/qb-shops#108]
**Describe the bug**
Before The weapon shop was Require Weapon License but now its gone 

**Expected behavior**
Should check Weapon licenses before weapon shop open 

**Questions (please complete the following information):**
 - When you last updated: [last week]
 - Are you using custom resource? which ones? [no]
 - Have you renamed `qb-` to something custom? no]

**Comment by GhzGarage** [comment]
Fixed
