### ISSUE TITLE
can approve pull weapon license to project

### ISSUE THREAD

**Issue by vanillla1** [qbcore-framework/qb-shops#11]
can approve pull weapon license to project

**Comment by JericoFX** [comment]
is this a issue?

**Comment by vanillla1** [comment]
@JericoFX yes

**Comment by vanillla1** [comment]
see here
if you dont see code

                        if IsControlJustPressed(0, 38) then -- E
			                SetWeaponSeries()
                            local ShopItems = {}
                            ShopItems.items = {}
                            QBCore.Functions.TriggerCallback('qb-shops:server:getLicenseStatus', function(result)
                                ShopItems.label = Config.Locations[shop]["label"]
                                if Config.Locations[shop].type == "weapon" then
                                    if result then
                                        ShopItems.items = Config.Locations[shop]["products"]
                                    else
                                        for i = 1, #Config.Locations[shop]["products"] do
                                            if not Config.Locations[shop]["products"][i].requiresLicense then
                                                table.insert(ShopItems.items, Config.Locations[shop]["products"][i])
                                            end
                                        end
                                    end

**Comment by JericoFX** [comment]
You open a issue instead of a pr, that's my point
