### ISSUE TITLE
[SUGGESTION] Server-Side Peds

### ISSUE THREAD

**Issue by GhzGarage** [qbcore-framework/qb-shops#110]
There have been multiple reports of ped issues (disappearing, etc). Need to move these to the server.

**Comment by Leslija** [comment]
I had the same problem. I had to restart the resource several times to spawn the peds again. 

I found a solution for me:
The bug causes Casino Ped.

I use a Linux server (No idea if that helps?).

**Comment by Dabcity** [comment]
This seems to be the only solution, Seems Peds spawned inside ytyps or ymaps disappear after some time.

**Comment by peppinoita** [comment]
What if we spawn peds only if a player is near and despawn when no players are aound?

**Comment by ChickenDipper1** [comment]
I've noticed this is caused when I use the /logout command as an admin...

**Comment by bluecraank** [comment]
Same problem... tried to move it to server but Invicible and Scenarios not working on ServerSide
