### ISSUE TITLE
[SUGGESTION] Option to disable / enable peds

### ISSUE THREAD

**Issue by SPKReality** [qbcore-framework/qb-shops#113]
**Is your feature request related to a problem? Please describe.**
Option to disable / enable peds

----------------------------

**Describe the feature you'd like**
just a small idea but a config to disable / enable peds so you dont have to edit each shop to stop the peds from spawning. 

-------------------------------

**Additional context**

**Comment by FlipDev2022** [comment]
Yes I like this..

**Comment by Dabcity** [comment]
If you set Config.UseTarget = false - Peds won't spawn it defaults to markers and 3d text instead of targets.

**Comment by i-kulgu** [comment]
@SPKReality , Like Dabcity said you can disable the Config.UseTarget to disable the spawning of peds. 
If you disable it, Drawtext will be used for the locations and if you enable you'll get Peds with target.
