### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mjvanhaastert** [qbcore-framework/qb-shops#117]
After granting a weapons license to a player and he goes to the weapon shop the playerdata is never updated, it still contains the old meta list. So when he wants to open the shop the PlayerData.metadata["licences"].weapon will return false if he doesnt relog.

**To Reproduce**
- grant a player a weapon license
- go to the weapon shop and try to open the shop
- you need to relog to fix this problem

**Expected behavior**
after granting a license there should be no need to relog to be able to buy a weapon.

**Questions (please complete the following information):**
- fully up to date server
- no custom scripts

if already put a pull request in and how to solve this simple issue #118

**Comment by r0adra93** [comment]
Awaiting to for https://github.com/qbcore-framework/qb-shops/pull/121 to be verified and merged into the system. This should resolve the issue.
