### ISSUE TITLE
[BUG] SCRIPT ERROR: @qb-shops/client/main.lua:81: attempt to index a nil value (field 'metadata')

### ISSUE THREAD

**Issue by davoucci** [qbcore-framework/qb-shops#120]
**Describe the bug**
i dont got any console error on start-up, but when i go shopping i cannot open the menu even if i see the notification. I got this error when i want to shopping ; SCRIPT ERROR: @qb-shops/client/main.lua:81: attempt to index a nil value (field 'metadata')
**To Reproduce**
1. Go to shop
2. Click on E to open the menu
3. See error

**Expected behavior**
It should open the menu

**Comment by r0adra93** [comment]
Awaiting to for https://github.com/qbcore-framework/qb-shops/pull/121 to be verified and merged into the system. This should resolve the issue.
