### ISSUE TITLE
[BUG] Weapon Licence is not working 

### ISSUE THREAD

**Issue by Polo4217** [qbcore-framework/qb-shops#125]
After granting weapon licence to player, they will buy it from cityhall go to weapon shop, but you still can't buy guns ect..  

Config.FirearmsLicenseCheck = true -- Whether a arms dealer checks for a firearms license

**Comment by Pardison** [comment]
same issue def a bug ever since a recent update to shops

**Comment by Provokke** [comment]
Yep same issue here to
