### ISSUE TITLE
[BUG?] Smoke on the water shop (counter collision issue with target?)

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-shops#127]
**Describe the bug**
Not 100% sure if it's me or not, but the ped behind the counter cannot be targeted anymore from the outside of the counter, if you clip behind him, you can interact. Noticed this since update 3 days ago and ran through the scripts to double check the updates.

Not 100% sure if it's just ours or it's an actual bug, but I guess it can be validated pretty quickly.

**To Reproduce**
1. Try use the ped at smoke on the water

**Expected behavior**
Target sees the ped and opens shop

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: 2 days
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? Yes

**Additional context**
I've tried to up the radius on the shop to 6.0 and then to 10.0 just to see and it doesn't do anything. Soon as I move the ped out from behind the counter it works: 
https://i.imgur.com/glXp4Ts.png

**Comment by ChickenDipper1** [comment]
This is a map issue, not related to the script.

**Comment by nzkfc** [comment]
Is that not a default location?

**Comment by ChickenDipper1** [comment]
It is but there is a collision I believe, use a mlo/ymap to replace the shop or remove it using codewalker.

**Comment by nzkfc** [comment]
Nah as in isn't it a default location for smoke on the water Ped for qb
shops? If it is, default location needs to move from behind the counter.

Odly this has worked for years but randomly stopped after the inventory has
item changes...
