### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xxUnknown13xx** [qbcore-framework/qb-shops#135]
unable to sell casino chips. I see the [E] but nothing happens when I press it. I can only buy chips, thats all.

**Comment by singh-manavv** [comment]
Any preview of the issue ? if you getting any errors , please provide a screenshot.

**Comment by Groundsloth123** [comment]
I cant sell my chips but there is no errors. this is a fresh install. no qb.notify or anything i press E and nothing happens.
