### ISSUE TITLE
DEFAULT INSTALL I GET THIS ERROR

### ISSUE THREAD

**Issue by Bongmasta406** [qbcore-framework/qb-shops#138]
[https://i.imgur.com/7xFyv07.png](url)

https://github.com/qbcore-framework/qb-shops/blob/5b75b1282149ee6922a44f6a64aa3de84905c577/config.lua#L433

**Comment by nzkfc** [comment]
Fresh? or did you add some products/shops? because right now that error is a common one where someone has forgotten to add a comma or wrap the items correctly. If you want put your config into here or pastebin and I can have a quick look for obvious stuff.
