### ISSUE TITLE
[BUG] Shop Inventory saves changes to all shops within the category

### ISSUE THREAD

**Issue by GpKkek** [qbcore-framework/qb-shops#148]
**Describe the bug**
Shop Inventory when using Config.UseTruckerJob = true is persistent for all shops per "products" category. For example, if you buy from one 24/7, then check another  you will notice the inventory has dropped for both. Shouldn't this only deduct from the current shop you are checking. This happens with Hardware, Liquor, Ammunition and Normal categories.

**To Reproduce**
1. Go to 247supermarket
2. Purchase an item
3. Go to 247supermarket2
4. Item has reduced from this store as well

**Expected behavior**
Item reduces from current shop's inventory, not all.

**Questions (please complete the following information):**
 - When you last updated: Yesterday
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? No

**Comment by eygi** [comment]
have you fixed this? i have same issue

**Comment by mistressUwU** [comment]
We found the issue, it's qb-target.
