### ISSUE TITLE
[SUGGESTION] option to be able to use objects aswell as peds with qb target

### ISSUE THREAD

**Issue by davedoink** [qbcore-framework/qb-shops#150]
**Is your feature request related to a problem? Please describe.**

No problem

**Describe the feature you'd like**

Just wondering how to use objects as targets aswell as peds 

**Describe alternatives you've considered**

n/a

**Additional context**

**Comment by rodrigoandrade1** [comment]
It is currently not possible to choose other objects or peds to add a target to, but I am working on optimizing this script and will do my best to add this option.
