### ISSUE TITLE
"No shop inventory found -- defaults enabled"

### ISSUE THREAD

**Issue by IamCodyy** [qbcore-framework/qb-shops#156]
Is this message normal? All the shops work with all of the items in them, trucker job is also disabled.

**Comment by ihustle662** [comment]
i have the same issue but my store wont open.

**Comment by Mjb1505** [comment]
Same issue, did anyone find a solution?

**Comment by taybandz1224** [comment]
anyone find a solution??

**Comment by IamCodyy** [comment]
I just commented out the print, shops still work as is.

**Comment by taybandz1224** [comment]
what do u mean i have the same issue but when i press e i get no menus and no error except the shop inventory no found.???

**Comment by kathryn2101** [comment]
im getting this error and i can open the shop but it wont let me buy anything in the shop

**Comment by ChiChixxTrigga** [comment]
> I just commented out the print, shops still work as is.

can you show a screenshot

**Comment by Yxngjefe** [comment]
getting the same issue when trying to open the shop , anyone have a solution for this :<

**Comment by citRaTTV** [comment]
This print is just informational. It means that the script didn't find an inventory for the shop in the json file, most likely because you're not using the truckerjob to refill stock.

**Comment by ChiChixxTrigga** [comment]
I had refill set to false
