### ISSUE TITLE
SCRIPT ERROR

### ISSUE THREAD

**Issue by OnlySOS** [qbcore-framework/qb-shops#163]
SCRIPT ERROR: @qb-shops/client/main.lua:55: attempt to indexa  nil value (upvalue 'shopInvJson') 

^^^This is what im recieivnig, it wont open the shop in the stores but will let you Target  the person. ive never touched teh code, even just replaced it.

**Comment by citRaTTV** [comment]
Do you have a `json/shops-inventory.json` file? If so what does it contain? I assume you have `Config.UseTruckerJob = false` in your config?

**Comment by OnlySOS** [comment]
@citRaTTV i just looked, apparently there was nothing in my json file.... like the code had been deleted. not sure hown that happened.

**Comment by citRaTTV** [comment]
> @citRaTTV i just looked, apparently there was nothing in my json file.... like the code had been deleted. not sure hown that happened.

You can grab a fresh copy from this repo

**Comment by OnlySOS** [comment]
@citRaTTV just re verified, the json provided here has only 2 lines of code. 
1. {
2. }

**Comment by OnlySOS** [comment]
@citRaTTV this will need an update, as im sure many will have this issue

**Comment by citRaTTV** [comment]
> @citRaTTV this will need an update, as im sure many will have this issue
> 

That's all that should be there. The script will write to it.

**Comment by OnlySOS** [comment]
@citRaTTV so is there something else causing my issue?

**Comment by OnlySOS** [comment]
![Screenshot 2024-01-28 232442](https://github.com/qbcore-framework/qb-shops/assets/158010616/342e080a-32fe-43b1-88e7-3274589a53ae)

**Comment by citRaTTV** [comment]
> ![Screenshot 2024-01-28 232442](https://private-user-images.githubusercontent.com/158010616/300342035-342e080a-32fe-43b1-88e7-3274589a53ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwOTE3NzUsIm5iZiI6MTcwODA5MTQ3NSwicGF0aCI6Ii8xNTgwMTA2MTYvMzAwMzQyMDM1LTM0MmUwODBhLTMyZmUtNDNiMS04OGU3LTMyNzQ1ODlhNTNhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQxMzUxMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTNhNjY0ZmQ4Mjk4YWY4NjQ5OWMxOGM0NjEwYmU5ODZkMzEwZjdhNjkxYTk4ZjMzZTU3Y2RjNDQ2NTA1ZDJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E6aq04O2dX_XdlOvhjn9eT5wusWMdwICvcozY1N3CXA)

@OnlySOS Again, this looks like an issue with the JSON file. Make sure that the file is in the proper location: https://github.com/qbcore-framework/qb-shops/blob/main/config.lua#L4 and isn't empty / contains malformed JSON. If you want to send along your config.lua and your shops-inventory.json, I'd be happy to have a look at them.

**Comment by ChiChixxTrigga** [comment]
> > ![Screenshot 2024-01-28 232442](https://private-user-images.githubusercontent.com/158010616/300342035-342e080a-32fe-43b1-88e7-3274589a53ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwOTE3NzUsIm5iZiI6MTcwODA5MTQ3NSwicGF0aCI6Ii8xNTgwMTA2MTYvMzAwMzQyMDM1LTM0MmUwODBhLTMyZmUtNDNiMS04OGU3LTMyNzQ1ODlhNTNhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQxMzUxMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTNhNjY0ZmQ4Mjk4YWY4NjQ5OWMxOGM0NjEwYmU5ODZkMzEwZjdhNjkxYTk4ZjMzZTU3Y2RjNDQ2NTA1ZDJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E6aq04O2dX_XdlOvhjn9eT5wusWMdwICvcozY1N3CXA)
> 
> @OnlySOS Again, this looks like an issue with the JSON file. Make sure that the file is in the proper location: https://github.com/qbcore-framework/qb-shops/blob/main/config.lua#L4 and isn't empty / contains malformed JSON. If you want to send along your config.lua and your shops-inventory.json, I'd be happy to have a look at them.

You think you can help me with mines im having sort of the same issue but its saying no shop inventory

**Comment by EdwinShima** [comment]
SCRIPT ERROR: @qb-shops/client/main.lua:173: attempt to index a nil value (upvalue 'playerData')
not sure what the problem is
