### ISSUE TITLE
[BUG] No shop inventory found -- defaults enabled

### ISSUE THREAD

**Issue by JJR-Scripts** [qbcore-framework/qb-shops#164]
Every time i open any shop i get this No shop inventory found -- defaults enabled. if i fly out of my city we lose all items

**Comment by GhzGarage** [comment]
That just means that you're not using the stock system, it doesn't affect anything

**Comment by ChiChixxTrigga** [comment]
How do you fix it? Do i just revert back to original qb-inventory? Im using a fork for it. ``
