### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kingblu617** [qbcore-framework/qb-shops#173]
![image](https://github.com/user-attachments/assets/8d0fa5b3-ca36-41bd-ba67-83e2e307d91d)

RegisterNetEvent('ps-inventory:server:OpenInventory', function(name, id, other)
		local src = source
		local ply = Player(src)
		local Player = QBCore.Functions.GetPlayer(src)
		if ply.state.inv_busy then
			return QBCore.Functions.Notify(src, Lang:t("notify.noaccess"), 'error')

The last line is the 1404 line, and I have no clue how to fix this... any help would be amazing

**Comment by Sanriku-Gaming** [comment]
We aren't ps... you should ask there.
