### ISSUE TITLE
shop and jobs

### ISSUE THREAD

**Issue by vanillla1** [qbcore-framework/qb-shops#20]
I hope you can add this option
The purchase is only open to those who hold the rank of a job
example
        [1] = {
            name = "cleaningkit",
            price = 125,
            amount = 25,
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "nitrous",
            price = 500,
            amount = 25,
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "repairkit",
            price = 125,
            amount = 25,
            type = "item",
            slot = 3,
             requiresJob = "mechanic"
        },
        [4] = {
            name = "advancedrepairkit",
            price = 250,
            amount = 25,
            info = {},
            type = "item",
            slot = 4,
            requiresJob = "mechanic"
        },

**Comment by BerkieBb** [comment]
Make the code and make a pull request or put suggestion in the title

**Comment by vanillla1** [comment]
@BerkieBb im edit title
