### ISSUE TITLE
Release It For qb-target also

### ISSUE THREAD

**Issue by GabbarFramework** [qbcore-framework/qb-shops#59]

**Comment by izMystic** [comment]
So you can sell it in your "gabbar framework"?

**Comment by GabbarFramework** [comment]
Nope i m realising scripts for free now

**Comment by ItsANoBrainer** [comment]
Already in progress.

**Comment by GabbarFramework** [comment]
> So you can sell it in your "gabbar framework"?

nope i m releasing my server for free
