### ISSUE TITLE
Weapons license does not work

### ISSUE THREAD

**Issue by SeriumTW** [qbcore-framework/qb-shops#63]
The gun license is not detected in the inventory and it doesn't let me take the weapons in the armory.

**Comment by Roberto0202** [comment]
police need to add your permissions

**Comment by SeriumTW** [comment]
How?

**Comment by Roberto0202** [comment]
you need to be sign in as police officer , then use /grantlicense ... easy bro next time chech script on server side for commands ;)

**Comment by Roberto0202** [comment]
you can also grab this coomand and put it in new job for adding license for weapons :D have fun. enjoy

**Comment by izMystic** [comment]
@SeriumTW @Roberto0202 can this be closed?
