### ISSUE TITLE
[BUG] Able to buy guns without license required

### ISSUE THREAD

**Issue by iktray** [qbcore-framework/qb-shops#64]
If you buy a knife in the gun store and then go back on the menu you can buy all the weapons that require a gun license.

**Comment by izMystic** [comment]
This is being looked into, please standby for a fix.

**Comment by iktray** [comment]
@izMystic Anything?

**Comment by izMystic** [comment]
nothing yet

**Comment by izMystic** [comment]
fixed in latest commit
