### ISSUE TITLE
hardware stores dont sell

### ISSUE THREAD

**Issue by parham-tehrani** [qbcore-framework/qb-shops#73]
when i go to normal shops. it works fine, i can make purchases, but when i go to a hardware store, and drag something, it doesn't sell me anything, nor deduct anything from my account.

**Comment by FjamZoo** [comment]
Hello, Which inventory are you using? We need a little more information as shops could be a cause of this but also a chance of this being the inventory.

I've tried and could not replicate on my setup.

**Comment by parham-tehrani** [comment]
thanks for your response, i am using the normal qb-inventory just changed up the html to more customized stuff

**Comment by bludgeru** [comment]
I have the same issue, can't buy nothing on hardware, weed shop etc. ammunation and normal stores are working

**Comment by bludgeru** [comment]
> when i go to normal shops. it works fine, i can make purchases, but when i go to a hardware store, and drag something, it doesn't sell me anything, nor deduct anything from my account.

I solved the issue go to qb-inventory -> server -> main-lua on line 745 add a 0 to second.maxweight Like this:				`secondInv.maxweight = 9000000`

**Comment by parham-tehrani** [comment]
i have migrated to a whole new server and OS, i'll try it again and if the problem is still there, i'll def fix what you had said and will mention it here... thank you so much

**Comment by parham-tehrani** [comment]
aight so after the whole new server n core and new build....the hardware stuff works perfectly fine.
but the gearshop doesn't work.  ican't buy from them,
i tried to increase that secndInv.maxweight but still the same issue ! :(

**Comment by BerkieBb** [comment]
This seems more like a qb-inventory issue than a qb-shops issue
