### ISSUE TITLE
Weapon License is not working correctly

### ISSUE THREAD

**Issue by twigmasters** [qbcore-framework/qb-shops#80]
**Describe the bug**
Was testing the weapon shops with a friend and as a cop I used "/grantlicense [ID] weapon" to give him a weapons license. He gets the notification but has nothing in his inventory. Then tries to buy a gun and still gets the message that he needs a license. So I did it again using the command and it says he has a license. 

I then used the same command to give one to myself and had the same result as a cop.

I looked in qb-core shared configs to make sure it is in the items list and weapons license is there.

anyone else run into this and know how to fix it?

**Comment by GhzGarage** [comment]
He needs to go buy it from city hall

**Comment by twigmasters** [comment]
so police use the command to grant it to a player and then they have to pick it up at city hall?
