### ISSUE TITLE
Nothing Works

### ISSUE THREAD

**Issue by Etcurate** [qbcore-framework/qb-shops#84]
No errors in live console just doesnt work in game I had made a error on the old shop script without peds now I updated to this one and it doesnt work Im using a different map but I load in Los Santos to test the server still not working and whenever you change cords it shows a error

**Comment by GhzGarage** [comment]
You didn’t say what doesn’t work

**Comment by GhzGarage** [comment]
![image](https://user-images.githubusercontent.com/57848836/162659007-7cf14e13-e7c0-4205-8805-94bbf991784a.png)

**Comment by GhzGarage** [comment]
![image](https://user-images.githubusercontent.com/57848836/162659045-115ede8c-fc50-4216-89e2-97797208117a.png)

**Comment by Etcurate** [comment]
Im going to see if I need QB-Target the config gave me a option to not use it so I didnt Im going to try that right now.


Also, Im going to show you how it looks whenever I change the location coords, it gives me a error around line 1169-1172 which is the beginning of the coords part of the scripts and doesn't really specify from there.

**Comment by Etcurate** [comment]
![FiveM® by Cfx re 4_11_2022 9_56_21 AM](https://user-images.githubusercontent.com/98551404/162756787-6795596e-d4ec-4c76-8326-e1c5e3693d8b.png)

![(1) txAdmin and 44 more pages - Personal - Microsoft​ Edge 4_11_2022 9_58_27 AM](https://user-images.githubusercontent.com/98551404/162757081-8199f12f-7b40-44c5-acea-dd7a16aac199.png)

![_g446466_gta5-fivem-txadmin_QBCoreFramework_E9F8A9 base_resources_ qb _qb-shops_config lua - etcurate@194 156 91 231 - Editor - WinSCP 4_11_2022 9_58_48 AM](https://user-images.githubusercontent.com/98551404/162757131-0ecdeabc-4e7f-43f0-997b-64489595ac05.png)

**Comment by Etcurate** [comment]
![ZAP-Hosting 2 0 Webinterface - Gameserver #1 194 156 91 231_30190 - Configs and 37 more pages - Personal - Microsoft​ Edge 4_11_2022 10_06_50 AM](https://user-images.githubusercontent.com/98551404/162757308-141b876d-405c-4270-b8d8-5032d3258bb4.png)

**Comment by Etcurate** [comment]
Sorry for the late response I just woke up

**Comment by BerkieBb** [comment]
Still an issue? I've tested both the drawtext and target option and they both work.
