### ISSUE TITLE
model's despawning after time

### ISSUE THREAD

**Issue by gypsychicken** [qbcore-framework/qb-shops#86]
I have been using the updated qb shops recently, am having an issue where the ped models in the stores are despawning after a period of time. ensuring the resource replaces the peds and works as expected.  

have not measured the time it take for them to despawn.

**Comment by SenseiSpringroll** [comment]
I am experiencing the same thing, trying to figure out what the issue could be

**Comment by 19adorest** [comment]
yeah me too

**Comment by SenseiSpringroll** [comment]
Are you guys using any sort of MLO?

**Comment by gypsychicken** [comment]
> Are you guys using any sort of MLO?

Yes and no. In some areas we have MLO's and other place we do not. Either way, all shop peds despawn.

**Comment by SenseiSpringroll** [comment]
> > Are you guys using any sort of MLO?
> 
> Yes and no. In some areas we have MLO's and other place we do not. Either way, all shop peds despawn.

Hmm yeah it's a bit confusing to say the least. I thought maybe the MLO's I'm using ( gabz ) could be the problem. But if it's still happening in standard interiors I have no idea what else it could be.

**Comment by Roberto0202** [comment]
RegisterNetEvent('QBCore:Client:OnPlayerLoaded', function()
    createBlips()
    createPeds()
end)

AddEventHandler('onResourceStart', function(resourceName)
    if GetCurrentResourceName() == resourceName then
        createBlips()
        createPeds()
    end
end)

RegisterNetEvent('QBCore:Client:OnPlayerUnload', function()
    deletePeds()
end)

AddEventHandler('onResourceStop', function(resourceName)
    if GetCurrentResourceName() == resourceName then
        deletePeds()
    end
end)

**Comment by Roberto0202** [comment]
this swich fixed it for me

**Comment by gypsychicken** [comment]
> QBCore:Client:OnPlayerUnload

What exactly did you change? It looks the same to me.

**Comment by 19adorest** [comment]
> 

this one already on the script mate

**Comment by 19adorest** [comment]
> RegisterNetEvent('QBCore:Client:OnPlayerLoaded', function() createBlips() createPeds() end)
> 
> AddEventHandler('onResourceStart', function(resourceName) if GetCurrentResourceName() == resourceName then createBlips() createPeds() end end)
> 
> RegisterNetEvent('QBCore:Client:OnPlayerUnload', function() deletePeds() end)
> 
> AddEventHandler('onResourceStop', function(resourceName) if GetCurrentResourceName() == resourceName then deletePeds() end end)

this one already on the script mate

**Comment by BerkieBb** [comment]
There is no code in qb-shops that despawns these peds after some time
