### ISSUE TITLE
Issues with spawning peds and using them

### ISSUE THREAD

**Issue by dvaturi** [qbcore-framework/qb-shops#92]
![16507155771898438484576811109247](https://user-images.githubusercontent.com/57751780/164893794-08e00ce4-e650-48e8-b937-716ca4bc895c.jpg)
some peds are not spawning, after using "restart qb-shops" in a row they spawn and others disappear. if i "scare" them they wont let me qb-target them anymore

**Comment by BerkieBb** [comment]
That looks like an issue from a third party resource as you're getting errors from the server console when the peds are spawned client side and non-networked in qb-shops
