### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jokernights** [qbcore-framework/qb-shops#96]
**Describe the bug**
Just downloaded the new qb-shops and started the server and this error pops up

**To Reproduce**
1. Go to 'fivem'
2. Click on 'my server'
3. Use this item 'can't get in to see' (item's name from shared.lua if applicable)

**Expected behavior**
to start up

**Screenshots**
![image](https://user-images.githubusercontent.com/77025615/169694750-cd197e20-358a-469b-aa25-10713e61076b.png)

**Questions (please complete the following information):**
 - Today
 - A lot [e.g. zdiscord]
 - Have you renamed `qb-` to something custom? NO[e.g. yes/no]

**Additional context**

**Comment by ggoodell2** [comment]
im having the same issue but it comes up as soon as i load into the server. only difference is after 202: it says bad argument #1 to 'vector3' (invalid vector type)

**Comment by Kpf1220** [comment]
im having same issue as you @ggoodell2
