### ISSUE TITLE
[BUG]issue on load in

### ISSUE THREAD

**Issue by ggoodell2** [qbcore-framework/qb-shops#99]
**Describe the bug**
error in f8 on loadin.
**To Reproduce**
1. load into server
2. Check f8
3. https://gyazo.com/547b25346d825120fea368a56f5a2f6c

**Expected behavior**
no error

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: all updates are current
 - Are you using custom resource? no]
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**

**Comment by BerkieBb** [comment]
Thid problem can only be caused if you configured something wrong in the config, so please re-check your config
